inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.1
  TargetRailsVersions: 6.0.3.4
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'lib/**/*'
    - 'config/puma.rb'
Rails:
  Enabled: true

# issueにも上がっているが解決していないよう
# https://github.com/rubocop-hq/rubocop-rails/issues/343
Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/users/registrations_controller.rb'

# フォロー機能の場合のInverseOfオプションが腹落ちしないため除外
Rails/InverseOf:
  Exclude:
    - 'app/models/user.rb'

# 自動修正するとエラーになる
Rails/DynamicFindBy:
  Enabled: false

Style/AsciiComments:
  Enabled: false

# ドキュメントの無い public class を許可する
Style/Documentation:
  Enabled: false

Style/IdenticalConditionalBranches:
  Exclude:
    - 'app/controllers/tickets_controller.rb'

Style/RedundantSelf:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - Gemfile
    - spec/**/*
    - config/routes.rb

Metrics/MethodLength:
  Max: 16
  Exclude:
    - app/controllers/cards_controller.rb

Metrics/AbcSize:
  Max: 23
  Exclude:
    - app/channels/room_channel.rb
    - app/controllers/tickets_controller.rb
    - app/controllers/rooms_controller.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - app/controllers/cards_controller.rb

Metrics/ClassLength:
  Exclude:
    - app/controllers/tickets_controller.rb

# エラーが起きた際、spec/rails_helper.rb内のsave_and_open_pageメソッドを実行する設定を見直す必要がある
Lint/Debugger:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/InstanceVariable:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/EmptyExampleGroup:
  Enabled: false
