inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.1
  TargetRailsVersions: 6.0.3.4
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'lib/**/*'
    - 'config/puma.rb'
Rails:
  Enabled: true

# issueにも上がっているが解決していないよう
# https://github.com/rubocop-hq/rubocop-rails/issues/343
Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/users/registrations_controller.rb'

# 自動修正するとエラーになる
Rails/DynamicFindBy:
  Enabled: true

Style/AsciiComments:
  Enabled: false

# ドキュメントの無い public class を許可する
Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - Gemfile
    - spec/**/*

Metrics/MethodLength:
  Max: 14

Metrics/AbcSize:
  Max: 23

RSpec/ExampleLength:
  Max: 8

RSpec/InstanceVariable:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/NestedGroups:
  Max: 4
