version: "3"
services:
  db:
    image: postgres
    platform: linux/amd64
    environment:
      POSTGRES_DATABASE: conefan_dev
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    build: .
    environment:
      EDITOR: vi
    tty: true
    stdin_open: true
    # rails sした際に、A server is already running.というエラーが出ることがある。これを防ぐため、rm -f tmp/pids/server.pidしている。
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
    ports:
      - "3100:3000"
    # depends_onでコンテナが起動する順番を制御する（この場合、db→web）
    depends_on:
      - db
volumes:
  bundle:
    driver: local
  postgres-data:
    driver: local
